### ISSUE TITLE
Spécifier la mise à jour des données

### ISSUE THREAD

**Issue by remidbs** [Envinorma/envinorma-data#119]
# Lorsqu'un AM est mis à jour 
Comme le lien entre la prescription et l'AM se fait par id de section + position dans la section, lorsqu'un AM est mis à jour, il est possible qu'il y ait un décalage entre l'alinéa sélectionné avant la mise à jour de l'AM et le nouvel alinéa. On pourrait donc supprimer seulement les prescriptions dont le texte a changé avec la mise à jour.
Pour cela, il faut que les id des AM restent les mêmes après un recreate (ce n'est pas le cas aujourd'hui) et il faut écrire le script de suppression des prescriptions.
Le plus simple est probablement des rester sur une suppression de toutes les prescriptions à chaque mise à jour des AM.

# Lorsqu'un nouveau batch de données géorisques arrive
Il y a donc de nouvelles installations et de nouveaux classements.
Aujourd'hui, lorsque cela arrive, on supprime toutes les prescriptions, installations et classements. 

## Cas des installations dupliquées
Aujourd'hui, on supprime toutes les installations dupliquées.
On pourrait être un peu plus fin : garder les versions dupliquées et les rattacher à la nouvelle version de l'installation. NB:
- il peut y avoir un décalage entre la nouvelle version de l'installation et la version dupliquée
- il faut garder l'ancien mapping entre les id S3IC et les id envinorma pour mettre à jour les liens avec l'installation dupliquée

## Cas des prescriptions
Aujourd'hui, on supprime toutes les prescriptions. 
Alternative : on pourrait refaire le mapping entre les prescriptions avec les anciennes installations et les nouvelles pour mettre à jour l'id.

# Alternative : mise à jour du diff des installations.
- On regarde quelles installations ont changé (une installation a changé si un de ses classement a changé ou un de ses attributs a changé)
- On regarde quelles installations ont été créées et supprimées.

Pour les installations créées : 
- On les crée (pas de problème particulier)

Pour les installations supprimées : 
- On supprime les classements et prescriptions associés 
- On supprime les installations
- Mais on ne supprime pas les copies de l'installations (elles sont désormais considérées comme de nouvelles installations)

Pour les installations modifiées : 
- On met à jour toutes les caractéristiques
- On recrée les classements
- On ne supprime pas les prescriptions
- On ne touche pas aux versions dupliquées

**Comment by lisa-durand** [comment]
Top tout ça ! 
Concernant la MAJ des AM, je me demande si on ne peut pas imaginer un système d’alerte tout simple ?
Qui dirait qqchose comme « il y a eu une MAJ, vos prescriptions peuvent-être décalées, n’hésitez pas à supprimer vos prescriptions. »

**Comment by remidbs** [comment]
Ah oui, bonne idée !
