### ISSUE TITLE
Ajouter une licence

### ISSUE THREAD

**Issue by bzg** [Envinorma/envinorma-data#33]
Voir la liste des licences autorisées ici: https://www.data.gouv.fr/fr/licences

A dispo si besoin!

**Comment by bzg** [comment]
Bonjour, je me permets de venir aux nouvelles - est-ce que ce dépôt est géré ?

**Comment by remidbs** [comment]
J'avais manqué cet issue, que j'ai remarqué à l'occasion d'un nettoyage des issues, merci!

**Comment by bzg** [comment]
Merci d'avoir ajouté la licence, et pas de souci pour le délai !
