### ISSUE TITLE
Bug à l'affichage de la page des prescriptions

### ISSUE THREAD

**Issue by alexandre-leonardi** [Envinorma/envinorma-data#77]
A la génération des prescriptions sur http://envinorma.herokuapp.com/installations/15043
[Btissaime Luzet sur Fééric]
- les prescriptions des APs ne sont pas toutes disponibles (faut-il à termes les scanner ? Comment avez-vous procédé?)
Réponse AL: demande de compléments pour identifier le bug

**Comment by lisa-durand** [comment]
à priori c'est ok maintenant qu'on a déployé cette PR qui améliore les perfs -> https://github.com/Envinorma/envinorma-web/pull/124
