### ISSUE TITLE
Bug - Site invisible

### ISSUE THREAD

**Issue by alexandre-leonardi** [Envinorma/envinorma-data#78]
[Webinaire, Juliette Le Reun]
Egalement Esso Raffinage à Port-Jérôme-sur-Seine 0058.00349
Exxonmobil chemical France à Port-Jérôme-sur-Seine 0058.00348

[Fééric, Emilie Oustric]
Une inspectrice ne trouve pas le site Total Raffinage France à Dunkerque, S3IC 0070.00918, présent sur géorisques:
https://www.georisques.gouv.fr/risques/installations/donnees/details/0070.00918#/
J'ai essayé, je ne trouve pas non plus (il y a plus de 10 sites à Dunkerque, plus de 10 sites Total Raffinage France, mais 0 réponses au n° S3IC)

**Comment by remidbs** [comment]
C'est parce que c'est un site SEVESO, je les ajoute.

**Comment by remidbs** [comment]
Corrigé au futur déploiement de l'app
