### ISSUE TITLE
L'arrêté TREP2008669A n'est pas dans sa version modifiée

### ISSUE THREAD

**Issue by alexandre-leonardi** [Envinorma/envinorma-data#92]
Mail 1 juin à Rémi et Lisa de Florent M.
super
juste un point de vigilance, je n'ai pas trouvé de version "modifiée" de l'arrêté de 2012 (par l'AM du 14/04/2020, NOR : TREP2008669A) ; ce qui impliquerait d'ajouter également ce dernier à la base de données...
merci pour votre travail, on gagne tous beaucoup de temps !

**Comment by remidbs** [comment]
Ce message est lié à #88 
Pour récapituler, pour les installations agréées VHU
- Il y a un AM de 2012 https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000025835110 
- Cet AM a été modifié en 2020 par un AM https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000041820083
Sur légifrance, il n'y a pas la version consolidée de l'AM de 2012, mais sur AIDA oui, j'ai donc ajouté la version AIDA de l'AM de 2012 (et je n'ai pas mis l'AM de 2020)
